/**
 * Self-hosted push via ntfy (issue #38).
 *
 * Web Push (lib/push.ts) always delivers through the browser's push
 * service — Google FCM for Chrome/Android, Apple APNs for Safari/iOS —
 * even when everything else in the stack is self-hosted. That leaks "this
 * user just got a notification" metadata to a third party.
 *
 * ntfy (https://ntfy.sh, self-hostable: https://github.com/binwiederhier/ntfy)
 * is a pub/sub notification service. When self-hosted (see the `ntfy`
 * service in docker-compose.yml) and subscribed to directly — via the ntfy
 * apps/web UI's own persistent connection to *your* server, not ntfy.sh —
 * no third party ever sees that a message was sent. This is an additional
 * delivery channel alongside Web Push, not a replacement: a user can rely
 * on it exclusively by leaving Web Push unsubscribed.
 *
 * Each user gets one private, unguessable topic (packages/db
 * ntfy_subscriptions.topic) generated by generateNtfyTopic(). Anyone who
 * knows a topic name can publish/read it on a plain ntfy server, so treat
 * it like a bearer credential — this is why it's a long random string
 * rather than something derived from the user's id or name.
 */
const NTFY_SERVER_URL = process.env.NTFY_SERVER_URL ?? ""
const NTFY_ACCESS_TOKEN = process.env.NTFY_ACCESS_TOKEN ?? ""
const NTFY_PUBLISH_TIMEOUT_MS = 10_000

const TOPIC_ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789"
const TOPIC_RANDOM_LENGTH = 32

/** Generates a private, unguessable ntfy topic name (~165 bits of entropy). */
export function generateNtfyTopic(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(TOPIC_RANDOM_LENGTH))
  let suffix = ""
  for (let i = 0; i < TOPIC_RANDOM_LENGTH; i++) {
    suffix += TOPIC_ALPHABET[(bytes[i] as number) % TOPIC_ALPHABET.length]
  }
  return `vortex-${suffix}`
}

/** Whether the server is configured to publish to a self-hosted ntfy instance. */
export function isNtfyConfigured(): boolean {
  return NTFY_SERVER_URL.length > 0
}

export interface NtfyPayload {
  title: string
  body: string
  url?: string
  icon?: string
}

/**
 * Publish a notification to a user's private ntfy topic.
 * Returns false (and logs) on any failure — callers treat ntfy as
 * best-effort, same as an individual Web Push subscription failing.
 *
 * Publishes to the server's *root* URL with `topic` in the JSON body, not
 * `{server}/{topic}` — ntfy's JSON publish API is documented to route on
 * the body's `topic` field only when the request targets the root
 * (https://docs.ntfy.sh/publish/#publish-as-json); posting JSON to a
 * topic-specific path is a different, plain-text-body endpoint.
 */
export async function publishNtfy(topic: string, payload: NtfyPayload): Promise<boolean> {
  if (!NTFY_SERVER_URL) return false

  try {
    const res = await fetch(NTFY_SERVER_URL.replace(/\/+$/, "") || "/", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(NTFY_ACCESS_TOKEN ? { Authorization: `Bearer ${NTFY_ACCESS_TOKEN}` } : {}),
      },
      body: JSON.stringify({
        topic,
        title: payload.title,
        message: payload.body,
        // "high" hints instant delivery to clients holding a foreground
        // connection — the whole point of self-hosting is to avoid relying
        // on a third-party wake-up channel for timely delivery.
        priority: 4,
        ...(payload.url ? { click: payload.url } : {}),
        ...(payload.icon ? { icon: payload.icon } : {}),
      }),
      signal: AbortSignal.timeout(NTFY_PUBLISH_TIMEOUT_MS),
    })

    if (!res.ok) {
      // Don't log any part of `topic` — it's a bearer credential (see module docstring).
      console.error(`publishNtfy: server responded ${res.status}`)
      return false
    }
    return true
  } catch (err) {
    console.error("publishNtfy: failed to reach ntfy server", err instanceof Error ? err.message : err)
    return false
  }
}
